### ISSUE TITLE
[FEEDSTOCK REQUEST] DeepSpeed v0.3.16

### ISSUE THREAD

**Issue by adammoody** [open-ce/open-ce#415] opened 2021-05-15 19:38 UTC
**Describe the package you'd like added**
Are there plans to add Microsoft's DeepSpeed support for PyTorch?

https://github.com/microsoft/DeepSpeed

**Describe how this package fits in with the project**

**Additional context**
I'm trying to get DeepSpeed v0.3.16 working on Power9 starting from a base Open-CE environment.  I am working through a series of issues, some of which are specific to PowerPC.  I am curious if you might have already solved some or all of those.

**Comment by jayfurmanek** [comment] 2021-05-17 02:54
Not yet, no.
Post them here though and maybe we can help you through it!

**Comment by adammoody** [comment] 2021-07-09 00:42
This is a work in progress.  I'll update this post as I figure things out.

I am building with CUDA 10.2.  I have a conda environment for deepspeed, based on OpenCE installed at a path like:
```
/path/to/anaconda/envs/deepspeed
```

Below, Triton and DeepSpeed are both built from source.  The default compilers on my system build with ``-D_GLIBCXX_USE_CXX11_ABI=0``, but the conda packages expect ``-D_GLIBCXX_USE_CXX11_ABI=0``.  To work around that, I found I had to install ``gxx_linux-ppc64le=7`` and set ``CC`` and ``CXX`` and use those compilers to build Triton and DeepSpeed.
```
conda install gxx_linux-ppc64le=7
export CC=/path/to/anaconda/envs/deepspeed/bin/powerpc64le-conda_cos7-linux-gnu-gcc
export CXX=/path/to/anaconda/envs/deepspeed/bin/powerpc64le-conda_cos7-linux-gnu-c++
```

DeepSpeed v0.3.16 includes a specific dependency on Triton v0.2.3.  However, that version of Triton does not install for PowerPC.  I did find that Triton v0.4 fares better when built from source.  On my system, the default compilers
```

git clone git@github.com:ptillet/triton.git
pushd triton
  # build with a newer triton release
  git checkout v0.4
  #git checkout v0.2.3

  pushd python
    python setup.py bdist_wheel
    pip install dist/triton*whl
  popd
```
I'm not entirely sure whether that is valid, but I do see that newer DeepSpeed versions have moved to newer Triton versions.

Some ops in DeepSpeed are not yet supported on PowerPC.  I selectively enable a subset of ops that I've gotten to build.  Some of those require patches which are done with ``sed`` commands below.
```
# https://www.deepspeed.ai/tutorials/advanced-install/
#export DS_BUILD_OPS=1 # toggles all ops
#export DS_BUILD_CPU_ADAM=1 # builds the CPUAdam op
export DS_BUILD_FUSED_ADAM=1 # builds the FusedAdam op (from apex)
export DS_BUILD_FUSED_LAMB=1 # builds the FusedLamb op
export DS_BUILD_SPARSE_ATTN=1 # builds the sparse attention op
#export DS_BUILD_TRANSFORMER=1 # builds the transformer op
#export DS_BUILD_STOCHASTIC_TRANSFORMER=1 # builds the stochastic transformer op
export DS_BUILD_UTILS=1 # builds various optimized utilities

git clone git@github.com:microsoft/DeepSpeed.git
pushd DeepSpeed
  git checkout v0.3.16

  # change dependency list to accept any version of triton
  sed -i 's/triton==0.2.3/triton/g' requirements/requirements-sparse_attn.txt

  # -march is not supported on PowerPC, use -mcpu instead
  sed -i 's/-march=native/-mcpu=native/g' build/lib/deepspeed/ops/op_builder/*
  sed -i 's/-march=native/-mcpu=native/g' build/lib/op_builder/*
  sed -i 's/-march=native/-mcpu=native/g' deepspeed/ops/op_builder/*
  sed -i 's/-march=native/-mcpu=native/g' op_builder/*

  python setup.py bdist_wheel

#  pip install dist/deepspeed*whl
  pip install --force-reinstall --no-deps dist/deepspeed*whl
popd
```
Because some ops are not built, there are certain parts of DeepSpeed that one cannot use at runtime.  One needs to avoid those by constructing a proper DeepSpeed config file.

**Comment by adammoody** [comment] 2021-07-09 01:55
I can additionally enable ``DS_BUILD_CPU_ADAM``:
```
export DS_BUILD_CPU_ADAM=1 # builds the CPUAdam op
```
with the following patch:
```
diff --git a/csrc/includes/cpu_adam.h b/csrc/includes/cpu_adam.h
index ed33b04..288db8f 100755
--- a/csrc/includes/cpu_adam.h
+++ b/csrc/includes/cpu_adam.h
@@ -1,10 +1,13 @@
 #pragma once
 
+#if (__x86_64__ || __i386__)
 #include <cpuid.h>
+#include <x86intrin.h>
+#endif
+
 #include <cuda_fp16.h>
 #include <cuda_runtime_api.h>
 #include <stdio.h>
-#include <x86intrin.h>
 #include <cassert>
 #include "context.h"
 #include "cublas_v2.h"
```
The corresponding C code uses lots of x86 macros to handle the Adam optimizer with vectorized CPU instructions, like ``SIMD_SET`` and ``SIMD_FMA``:

https://github.com/microsoft/DeepSpeed/blob/aeea85b45071a44fb1d2f9d9a60cdf28bcf05849/csrc/adam/cpu_adam.cpp#L38

I'm guessing there may be PowerPC equivalents that one could use.  If so, perhaps someone could implement something for Power.

**Comment by adammoody** [comment] 2021-07-09 02:56
When I enable the transformer op:
```
export DS_BUILD_TRANSFORMER=1 # builds the transformer op
```
I get an error like the following:
```
csrc/transformer/normalize_kernels.cu(880): error: no operator "*=" matches these operands
            operand types are: __half2 *= __half2
```
A work around listed in the issue here seems to work:
https://github.com/microsoft/DeepSpeed/issues/750
```
export TORCH_CUDA_ARCH_LIST=7.0
```
With that in place, I could then enable both:
```
export DS_BUILD_TRANSFORMER=1 # builds the transformer op
export DS_BUILD_STOCHASTIC_TRANSFORMER=1 # builds the stochastic transformer op
```

**Comment by jayfurmanek** [comment] 2021-07-09 05:49
Great work! I don't see anything here that couldn't get translated into a conda recipe.
Triton would get its own recipe - we are updating Transoformers now.

That Adam optimizer in DeepSpeed looks fully vectored out for AVX256 and AVX512. Running it scalar on ppc64le would certainly result in a much slower optimizer. VSX support could be added for ppc, but that would be a chunk of work since VSX uses 128bit vectors.

Are the other DeepSpeed ops you left disabled also highly tuned for AVX?

**Comment by adammoody** [comment] 2021-07-09 19:00
> Are the other DeepSpeed ops you left disabled also highly tuned for AVX?

Besides ``adam/cpu_adam.cpp``, it looks like ``aio/py_lib/deepspeed_py_copy.cpp`` also has some SIMD/AVX instructions.  These are also the only two ops that have an ``-march=native`` flag:
```
op_builder/async_io.py
op_builder/cpu_adam.py
```
I don't believe the rest of the ops have any AVX.

It looks like the aio op was auto-disabled in the build because it failed to find ``libaio-dev``:
```
 [WARNING]  async_io requires the libraries: ['libaio-dev'] but are missing. Can be fixed by: `apt install libaio-dev`.
```
during the check here:

https://github.com/microsoft/DeepSpeed/blob/master/op_builder/async_io.py#L55-L62

I can now drop all of the individual selections and just build with:
```
export DS_BUILD_OPS=1 # toggles all ops
```
I think everything but aio is building:
```
Install Ops={'cpu_adam': 1, 'fused_adam': 1, 'fused_lamb': 1, 'sparse_attn': 1, 'transformer': 1, 'stochastic_transformer': 1, 'async_io': False, 'transformer_inference': 1, 'utils': 1, 'quantizer': 1}
```

**Comment by adammoody** [comment] 2021-07-09 19:59
Debugging the aio op a bit more...  It looks for ``libaio-dev``:

https://github.com/microsoft/DeepSpeed/blob/aeea85b45071a44fb1d2f9d9a60cdf28bcf05849/op_builder/async_io.py#L56

using ``dpkg -l``:

https://github.com/microsoft/DeepSpeed/blob/aeea85b45071a44fb1d2f9d9a60cdf28bcf05849/op_builder/builder.py#L156

but the library is ``libaio-devel`` on my system, which is Redhat, so one has to use ``rpm -q -l`` instead.  I can hack those in with this patch:
```
diff --git a/op_builder/async_io.py b/op_builder/async_io.py
index 5041734..16b532e 100644
--- a/op_builder/async_io.py
+++ b/op_builder/async_io.py
@@ -53,7 +53,7 @@ class AsyncIOBuilder(OpBuilder):
         return ['-laio']
 
     def is_compatible(self):
-        aio_libraries = ['libaio-dev']
+        aio_libraries = ['libaio-dev', 'libaio-devel']
         aio_compatible = self.libraries_installed(aio_libraries)
         if not aio_compatible:
             self.warning(
diff --git a/op_builder/builder.py b/op_builder/builder.py
index 97ae936..7cb0d37 100644
--- a/op_builder/builder.py
+++ b/op_builder/builder.py
@@ -145,9 +145,8 @@ class OpBuilder(ABC):
 
     def libraries_installed(self, libraries):
         valid = False
-        check_cmd = 'dpkg -l'
         for lib in libraries:
-            result = subprocess.Popen(f'dpkg -l {lib}',
+            result = subprocess.Popen(f'rpm -q -l {lib}',
                                       stdout=subprocess.PIPE,
                                       stderr=subprocess.PIPE,
                                       shell=True)
```
One then needs to hide ``cpuid.h`` and ``x86intrin.h`` as with CPU_ADAM:
```
diff --git a/csrc/aio/py_lib/deepspeed_py_copy.h b/csrc/aio/py_lib/deepspeed_py_copy.h
index 823c298..819d568 100644
--- a/csrc/aio/py_lib/deepspeed_py_copy.h
+++ b/csrc/aio/py_lib/deepspeed_py_copy.h
@@ -6,8 +6,10 @@ Licensed under the MIT license.
 Functionality for swapping optimizer tensors to/from (NVMe) storage devices.
 */
 
+#if (__x86_64__ || __i386__)
 #include <cpuid.h>
 #include <x86intrin.h>
+#endif
 
 #include <deepspeed_aio_common.h>
 #include <stdlib.h>
```
However, it then fails the compile when it can't find ``libaio.h``:
```
In file included from csrc/aio/common/deepspeed_aio_common.h:8:0,
                 from csrc/aio/py_lib/deepspeed_py_copy.h:14,
                 from csrc/aio/py_lib/deepspeed_py_copy.cpp:8:
csrc/aio/common/deepspeed_aio_utils.h:15:10: fatal error: libaio.h: No such file or directory
 #include <libaio.h>
```
My system install is in ``/usr/include/libaio.h``, but it doesn't look there since it's using the conda gcc ``powerpc64le-conda_cos7-linux-gnu-gcc``.

I tried a ``conda install libaio``, but the compile is not including the path to that header either ``/path/to/anaconda/envs/deepspeed/include/libaio.h``.

**Comment by cdeepali** [comment] 2021-07-12 07:17
To include the header pls try build with `export CXXFLAGS="${CXXFLAGS} -I${CONDA_PREFIX}/include"`

**Comment by adammoody** [comment] 2021-07-12 19:25
> 
> 
> To include the header pls try build with `export CXXFLAGS="${CXXFLAGS} -I${CONDA_PREFIX}/include"`

Ah, yes.  That works.  I can build async_io op now.  Thanks @cdeepali !

**Comment by adammoody** [comment] 2021-07-16 20:44
I've got PRs in process with the DeepSpeed team to integrate some of these patches upstream.  I'll come back to update this issue with my current build process once those settle.

**Comment by jwitos** [comment] 2021-08-05 05:31
Hi @adammoody, I noticed that all PRs above have been merged to DeepSpeed repo. First of all, thank you for your efforts to integrate this with Open-CE. Me and my colleagues are very much interested in this use case as well. Did you have any luck building Open-CE with DeepSpeed after those PRs?

**Comment by adammoody** [comment] 2021-08-05 22:28
@jwitos , glad to help.  Yes, I think that I have DeepSpeed working within an Open-CE environment.

It's not complete in that proper Opce-CE packages don't exist for everything.  I'm using Open-CE as a base install, conda/pip installing various requirements, and then building a couple other things into wheels from source.

Also, someone who has some PowerPC assembly skills know-how should eventually take a stab at creating a PowerPC implementation of the Adam CPU op.  On PowerPC, this op falls back to a non-vectorized implementation, so it's likely much slower than the same op on x86 that is vectorized with AVX SIMD instructions.

I'll post follow up instructions later today or tomorrow.  I need to test them once more.

**Comment by jwitos** [comment] 2021-08-10 10:40
Thanks a lot @adammoody. If you have a chance to share your notes/instructions that would be very helpful, and I'd be more than happy to reproduce the installation steps.

**Comment by adammoody** [comment] 2021-08-10 21:37
@jayfurmanek , here are the instructions to get an Open CE conda environment with a DeepSpeed build.  This uses a lot of Open CE conda packages as a base, with some additional packages installed by pip, and a few built from source.
```
#!/bin/bash
envname="deepspeed"
installdir=`pwd`/anaconda

# install anaconda (8 minutes)
bash ./Miniconda3-latest-Linux-ppc64le.sh -b -f -p $installdir

# activate anaconda environment
source $installdir/bin/activate
 
# register local conda channel for Open-CE
condachannel=/path/to/opence/condabuild-1.2
conda config --prepend channels file://$condachannel
  
# create an opence environment in conda (Python-3.7)
conda create -y -n $envname python=3.7
  
# activate the opence environment
conda activate $envname

# need to compile triton and deepspeed wheels with these to get
conda install gxx_linux-ppc64le=7 -D_GLIBCXX_USE_CXX11_ABI=1

conda install -y pytorch
conda install -y torchvision
conda install -y pyarrow

pip install absl-py termcolor wrapt
pip install datasets

# can't remember if mpi4py is necessary, but just in case ...
wget https://bitbucket.org/mpi4py/mpi4py/downloads/mpi4py-3.0.3.tar.gz
tar xf mpi4py-3.0.3.tar.gz
pushd mpi4py-3.0.3
  python setup.py bdist_wheel
popd

# use conda gcc to build triton and deepspeed wheels
export CC=${CONDA_PREFIX}/bin/powerpc64le-conda_cos7-linux-gnu-gcc
export CXX=${CONDA_PREFIX}/bin/powerpc64le-conda_cos7-linux-gnu-c++

# build and install triton wheel, just tried the very latest, but hit errors
# the version I have been using is v0.4
git clone git@github.com:ptillet/triton.git
pushd triton
  git checkout v0.4
  pushd python
    python setup.py bdist_wheel
    pip install dist/triton*whl
  popd
popd

# install libaio into conda to compile deepspeed async_io op
conda install libaio

conda install tensorboardX
conda install ninja

# https://github.com/microsoft/DeepSpeed/issues/750
export TORCH_CUDA_ARCH_LIST=7.0

# https://www.deepspeed.ai/tutorials/advanced-install/
export DS_BUILD_OPS=1 # toggles all ops

# so that conda gcc compilers will find libaio.h and libaio.so in deepspeed configure test
export CFLAGS="-I${CONDA_PREFIX}/include $CFLAGS"
export LDFLAGS="-L${CONDA_PREFIX}/lib $LDFLAGS"

# checkout recent tag of deepspeed, build and install wheel
git clone git@github.com:microsoft/DeepSpeed.git
pushd DeepSpeed
  git checkout v0.4.5

  python setup.py bdist_wheel
  pip install dist/deepspeed*whl
popd
```
Assuming that all works, there's a good chance may also want HuggingFace transformers and tokenizers.  You can get those from Open CE, as well, but I haven't listed the steps here.

**Comment by amorehead** [comment] 2022-02-05 21:12
Out of curiosity, has this build script successfully been converted into a feedstock for easy ingestion on PowerPC platforms like Summit?

**Comment by npanpaliya** [comment] 2022-02-07 06:57
No, we have not added any feedstock for this yet.

**Comment by alexlang74** [comment] 2022-05-01 18:16
Hi @adammoody and @amorehead - is deep speed still relevant for you?

**Comment by amorehead** [comment] 2022-05-01 18:53
Hi, @alexlang74. I would say yes, although at the moment I have found a few workarounds to get DeepSpeed set up on Summit

**Comment by alexlang74** [comment] 2022-05-01 19:14
Thanks for the prompt response, @amorehead ! This helps us in our prioritization...

**Comment by alexlang74** [comment] 2022-11-15 10:02
Tentatively tracked for OpenCE 1.8: https://github.com/open-ce/open-ce/issues/706

**Comment by alexlang74** [comment] 2022-12-14 10:23
Delivered in OpenCE 1.8

**Closed by alexlang74** 2022-12-14 10:23 UTC
Labels: Feedstock Request
