### ISSUE TITLE
[FEEDSTOCK REQUEST] Pola-rs

### ISSUE THREAD

**Issue by madmax-codewarrior-0** [open-ce/open-ce#889] opened 2023-09-25 21:11 UTC
**Describe the package you'd like added**

Website: https://www.pola.rs/
Source: https://github.com/pola-rs/polars

**Describe how this package fits in with the project**
A fast library written in Rust for working with DataFrames in memory, built to the Apache Arrow spec. Speed is the primary goal.

**Additional context**
\* submitted on behalf from Open-CE users at US Bank

**Comment by cdeepali** [comment] 2024-09-10 08:43
Closing this, as it is duplicate of #1029

**Closed by cdeepali** 2024-09-10 08:43 UTC
